
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import threading
import time
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

import numpy
import pyaudio

BITRATE = 96000                                     # change to 44100 if performance issues
def sinOsc(frequency, duration, amplitude=.5):      # 50% volume
    nframes = duration * BITRATE
    frames = numpy.arange(nframes)
    frame_frequency = frequency / BITRATE
    val = amplitude * numpy.sin(frames * frame_frequency * 2.0 * numpy.pi)
    return val.astype(dtype=numpy.float32)

pa = pyaudio.PyAudio()
stream = pa.open(format=pyaudio.paFloat32, channels=2, rate=BITRATE, output=True)
signal_left = 0
signal_right = 0

RESET = False

def generate_delta05():
    """BUGGY!"""
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=60.0, duration=1.0)
    signal_right = sinOsc(frequency=60.5, duration=1.0)
    play_beat()
    RESET = True

def generate_delta2():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=60.0, duration=1.0)
    signal_right = sinOsc(frequency=62, duration=1.0)
    play_beat()
    RESET = True

def generate_delta1():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=60.0, duration=1.0)
    signal_right = sinOsc(frequency=61, duration=1.0)
    play_beat()
    RESET = True

def generate_theta3():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=60.0, duration=1.0)
    signal_right = sinOsc(frequency=63, duration=1.0)
    play_beat()
    RESET = True

def generate_theta4():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=60.0, duration=1.0)
    signal_right = sinOsc(frequency=64, duration=1.0)
    play_beat()
    RESET = True

def generate_theta5():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=60.0, duration=1.0)
    signal_right = sinOsc(frequency=65, duration=1.0)
    play_beat()
    RESET = True

def generate_theta6():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=60.0, duration=1.0)
    signal_right = sinOsc(frequency=66, duration=1.0)
    play_beat()
    RESET = True

def generate_alpha12():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=70.0, duration=1.0)
    signal_right = sinOsc(frequency=82.0, duration=1.0)
    play_beat()
    RESET = True

def generate_alpha11():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=70.0, duration=1.0)
    signal_right = sinOsc(frequency=81.0, duration=1.0)
    play_beat()
    RESET = True

def generate_alpha10():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=70.0, duration=1.0)
    signal_right = sinOsc(frequency=80.0, duration=1.0)
    play_beat()
    RESET = True

def generate_alpha9():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=70.0, duration=1.0)
    signal_right = sinOsc(frequency=79.0, duration=1.0)
    play_beat()
    RESET = True

def generate_alpha8():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=70.0, duration=1.0)
    signal_right = sinOsc(frequency=78.0, duration=1.0)
    play_beat()
    RESET = True

def generate_alpha7():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=70.0, duration=1.0)
    signal_right = sinOsc(frequency=77.0, duration=1.0)
    play_beat()
    RESET = True

def generate_beta13():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=80.0, duration=1.0)
    signal_right = sinOsc(frequency=93.0, duration=1.0)
    play_beat()
    RESET = True

def generate_beta14():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=80.0, duration=1.0)
    signal_right = sinOsc(frequency=94.0, duration=1.0)
    play_beat()
    RESET = True

def generate_beta15():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=80.0, duration=1.0)
    signal_right = sinOsc(frequency=91.0, duration=1.0)
    play_beat()
    RESET = True

def generate_beta16():
    global signal_right
    global signal_left
    global RESET
    signal_left = sinOsc(frequency=80.0, duration=1.0)
    signal_right = sinOsc(frequency=96.0, duration=1.0)
    play_beat()
    RESET = True


def play_beat():
    global signal_right
    global signal_left
    global RESET
    def thread_play():
        global RESET
        stereo_signal = numpy.ravel(numpy.column_stack((signal_left, signal_right)))
        while RESET == True:
            stream.write(stereo_signal.tobytes())
        #stream.stop_stream()
        #stream.close()
        #pa.terminate()

    if RESET == False:
        RESET = True
        threading.Thread(target=thread_play).start()
    else:
        RESET = False
        time.sleep(1)
        threading.Thread(target=thread_play).start()


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    387.0,
    23.0,
    anchor="nw",
    text="Binaural Beat Generator",
    fill="#000000",
    font=("Roboto", 48 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=generate_alpha11,
    relief="flat"
)
button_1.place(
    x=121.0,
    y=304.0,
    width=281.0,
    height=38.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=generate_theta5,
    relief="flat"
)
button_2.place(
    x=498.0,
    y=304.0,
    width=281.0,
    height=38.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=generate_beta13,
    relief="flat"
)
button_3.place(
    x=871.0,
    y=244.0,
    width=281.0,
    height=38.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=generate_alpha10,
    relief="flat"
)
button_4.place(
    x=121.0,
    y=364.0,
    width=281.0,
    height=38.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=generate_theta3,
    relief="flat"
)
button_5.place(
    x=498.0,
    y=364.0,
    width=281.0,
    height=38.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=generate_beta14,
    relief="flat"
)
button_6.place(
    x=871.0,
    y=304.0,
    width=281.0,
    height=38.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=generate_alpha12,
    relief="flat"
)
button_7.place(
    x=121.0,
    y=244.0,
    width=281.0,
    height=38.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=generate_theta6,
    relief="flat"
)
button_8.place(
    x=498.0,
    y=244.0,
    width=281.0,
    height=38.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=generate_delta05,
    relief="flat"
)
button_9.place(
    x=498.0,
    y=544.0,
    width=281.0,
    height=38.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=generate_alpha11,
    relief="flat"
)
button_10.place(
    x=121.0,
    y=424.0,
    width=281.0,
    height=38.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=generate_delta2,
    relief="flat"
)
button_11.place(
    x=498.0,
    y=424.0,
    width=281.0,
    height=38.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=generate_beta15,
    relief="flat"
)
button_12.place(
    x=871.0,
    y=364.0,
    width=281.0,
    height=38.0
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=generate_alpha8,
    relief="flat"
)
button_13.place(
    x=121.0,
    y=484.0,
    width=281.0,
    height=38.0
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=generate_alpha7,
    relief="flat"
)
button_14.place(
    x=121.0,
    y=544.0,
    width=281.0,
    height=38.0
)

button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    borderwidth=0,
    highlightthickness=0,
    command=generate_delta1,
    relief="flat"
)
button_15.place(
    x=498.0,
    y=484.0,
    width=281.0,
    height=38.0
)

button_image_16 = PhotoImage(
    file=relative_to_assets("button_16.png"))
button_16 = Button(
    image=button_image_16,
    borderwidth=0,
    highlightthickness=0,
    command=generate_beta16,
    relief="flat"
)
button_16.place(
    x=871.0,
    y=424.0,
    width=281.0,
    height=38.0
)

canvas.create_text(
    920.0,
    58.0,
    anchor="nw",
    text="Be careful with beta waves.\nThey can cause anxiety.\nUse these for strong concentration.",
    fill="#000000",
    font=("Roboto", 16 * -1)
)

canvas.create_text(
    532.0,
    620.0,
    anchor="nw",
    text="Delta recommended for sleep.\nTheta for deep meditation.",
    fill="#000000",
    font=("Roboto", 16 * -1)
)

canvas.create_text(
    156.0,
    620.0,
    anchor="nw",
    text="Awake but alert. \nUse this for meditation\nand concentrating.",
    fill="#000000",
    font=("Roboto", 16 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    1017.0,
    177.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    640.0,
    177.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    263.0,
    177.0,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
